# buildation
FROM alpine:3.11.6 AS builder

# ENV GOLANG_VERSION 1.14
ENV GOLANG_VERSION 1.13

ADD . /go/src/github.com/user/scraping-go
WORKDIR /go/src/github.com/user/scraping-go

RUN set -eux; \
      apk add --no-cache --virtual .build-deps \
        go~=$GOLANG_VERSION \
        gcc \
      ; \
      \
      go get -d -v; \
      CGO_ENABLED=1 go build -o ./scraping_web;

# Execution
FROM alpine:3.11.6

COPY --from=builder /go/src/github.com/user/scraping-go .

CMD ["./scraping_web"]
